repository:
  description: "Components with Kreftforeningen design tokens."
  homepage: "https://www.npmjs.com/package/@kreftforeningen/web-react"
  topics:
    - react
    - typescript
    - component-library
    - radix-ui
    - shadcn-ui
    - ui-components
    - design-system
    - accessible
    - vite
    - npm-package

  private: false
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_auto_merge: false
  delete_branch_on_merge: false
  allow_update_branch: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
